server:
  port: 8085

spring:
  application:
    name: shipping-service
  
  data:
    mongodb:
      host: localhost
      port: 27013
      database: shipping_db
#      uri: mongodb://localhost:27013/inventory-db
#      username: admin
#      password: password
#      authentication-database: admin

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    mss: DEBUG
