# Server Configuration
server:
  port: 8082

# Application Configuration  
spring:
  application:
    name: inventory-service
  
  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27012/inventory_db
      database: inventory_db

# Logging
logging:
  level:
    org.springframework.web: DEBUG
    mis: DEBUG
    org.springframework.data.mongodb: DEBUG